/* @v0idd0/interviewprep — pure-function brief serializers.
   Exports: formatBrief, validateBrief, simplifyBrief, FORMATS
   No DOM. No node-only globals. Works in any JS runtime that has Date + JSON. */

'use strict';

function escapeMarkdown(s) {
  if (!s) return '';
  return String(s).replace(/[\[\]\\`*_]/g, ch => '\\' + ch);
}

function asString(v) {
  if (v === null || v === undefined) return '';
  return String(v);
}

function validateBrief(brief) {
  if (!brief || typeof brief !== 'object') {
    throw new Error('brief must be an object');
  }
  if (!Array.isArray(brief.questions)) {
    throw new Error('brief.questions must be an array');
  }
  if (brief.company && typeof brief.company !== 'object') {
    throw new Error('brief.company must be an object if present');
  }
  return true;
}

function simplifyBrief(brief) {
  validateBrief(brief);
  return {
    role: asString(brief.role) || null,
    org: asString(brief.org) || null,
    questions: brief.questions.map(q => ({
      q: asString(q && q.q) || null,
      star: asString(q && q.star) || null,
    })),
    company: {
      summary: asString(brief.company && brief.company.summary) || null,
      facts: (brief.company && brief.company.facts && typeof brief.company.facts === 'object')
        ? Object.fromEntries(
            Object.entries(brief.company.facts).map(([k, v]) => [String(k), asString(v)])
          )
        : {},
    },
  };
}

function fmtMarkdown(brief) {
  const b = simplifyBrief(brief);
  const dt = new Date().toISOString().replace('T', ' ').replace(/\.\d+Z$/, ' UTC');
  let out = '# ' + escapeMarkdown(b.role || 'Interview Prep Brief') + '\n';
  if (b.org) out += '_' + escapeMarkdown(b.org) + '_\n';
  out += '\n_generated ' + dt + '_\n\n';
  out += '## 5 likely questions\n\n';
  b.questions.forEach((q, i) => {
    out += (i + 1) + '. ' + escapeMarkdown(q.q || '(no question)') + '\n';
    if (q.star) out += '   - **STAR:** ' + escapeMarkdown(q.star) + '\n';
    out += '\n';
  });
  if (b.company.summary || Object.keys(b.company.facts).length) {
    out += '## Company\n\n';
    if (b.company.summary) out += escapeMarkdown(b.company.summary) + '\n\n';
    const facts = Object.entries(b.company.facts);
    if (facts.length) {
      out += '| key | value |\n|---|---|\n';
      for (const [k, v] of facts) out += '| ' + escapeMarkdown(k) + ' | ' + escapeMarkdown(v) + ' |\n';
      out += '\n';
    }
  }
  out += '---\n_Generated by interviewprep · vøiddo._\n';
  return out;
}

function fmtPlain(brief) {
  const b = simplifyBrief(brief);
  let out = (b.role || 'Interview Prep Brief') + '\n';
  if (b.org) out += b.org + '\n';
  out += '─'.repeat(40) + '\n\n';
  out += '5 likely questions:\n\n';
  b.questions.forEach((q, i) => {
    out += (i + 1) + '. ' + (q.q || '(no question)') + '\n';
    if (q.star) out += '   STAR: ' + q.star + '\n';
    out += '\n';
  });
  if (b.company.summary || Object.keys(b.company.facts).length) {
    out += 'Company\n' + '─'.repeat(40) + '\n';
    if (b.company.summary) out += b.company.summary + '\n\n';
    for (const [k, v] of Object.entries(b.company.facts)) out += '  ' + k + ': ' + v + '\n';
    out += '\n';
  }
  return out;
}

function fmtJson(brief) {
  const b = simplifyBrief(brief);
  const out = {
    generated_at: new Date().toISOString(),
    tool: 'interviewprep',
    role: b.role,
    org: b.org,
    questions: b.questions,
    company: b.company,
  };
  return JSON.stringify(out, null, 2) + '\n';
}

function fmtReadme(brief) {
  const b = simplifyBrief(brief);
  const dt = new Date().toISOString().slice(0, 10);
  let out = '# ' + (b.role || 'Interview Prep') + ' — prep brief\n\n';
  if (b.org) out += '> ' + b.org + ' · prepared ' + dt + ' via [interviewprep](https://extensions.voiddo.com/interviewprep/).\n\n';
  else out += '> Prep brief generated ' + dt + ' via [interviewprep](https://extensions.voiddo.com/interviewprep/).\n\n';
  out += '## What to expect\n\n';
  out += b.questions.length + ' likely interview questions, each with a STAR-format answer scaffold so you walk in with structured answers, not improvised ones.\n\n';
  out += '## Questions\n\n';
  b.questions.forEach((q, i) => {
    out += '### Q' + (i + 1) + '. ' + escapeMarkdown(q.q || '(no question)') + '\n\n';
    if (q.star) out += '**STAR scaffold:** ' + escapeMarkdown(q.star) + '\n\n';
  });
  if (b.company.summary || Object.keys(b.company.facts).length) {
    out += '## Company research\n\n';
    if (b.company.summary) out += escapeMarkdown(b.company.summary) + '\n\n';
    const facts = Object.entries(b.company.facts);
    if (facts.length) {
      for (const [k, v] of facts) out += '- **' + escapeMarkdown(k) + ':** ' + escapeMarkdown(v) + '\n';
      out += '\n';
    }
  }
  out += '---\n\n_Built by [vøiddo](https://voiddo.com), a small studio shipping AI-flavoured tools, browser extensions and weird browser games._\n';
  return out;
}

const FORMATTERS = {
  markdown: fmtMarkdown,
  plain:    fmtPlain,
  json:     fmtJson,
  readme:   fmtReadme,
};

const FORMATS = Object.keys(FORMATTERS);

function formatBrief(brief, format) {
  const fn = FORMATTERS[format] || FORMATTERS.markdown;
  return fn(brief);
}

module.exports = {
  formatBrief,
  validateBrief,
  simplifyBrief,
  FORMATS,
};
